### ISSUE TITLE
Register emissions source ID and institution ID

### ISSUE THREAD

**Issue by znichollscr** [PCMDI/input4MIPs_CVs#55]
For the CEDS produced data, we need a source ID and institution ID entry.

Institution ID will be a bit tricky I expect. From what I can tell, the institute is either CEDS or JGCRI. They both appear to be a consortium of PNNL and University of Maryland. Once we have clarity on this, I can help push this upstream to https://github.com/PCMDI/mip-cmor-tables.

In terms of source ID, suggestion below (same idea as https://github.com/PCMDI/input4MIPs_CVs/issues/42)

```json
    "CEDS-YYYY-mm-DD":{
        "contact":"rachel.hoesly@pnnl.gov;ssmith@pnnl.gov;noah.prime@pnnl.gov",
        "further_info_url":"www.tbd.invalid",
        "institution_id":"CEDS",
        "license_id":"CC BY 4.0",
        "mip_era":"CMIP6Plus",
        "source_version":"YYYY.mm.DD"
    }
```

**Comment by hahsan1** [comment]
Hi @znichollscr I am working on preparing the CEDS gridded emissions files for validation. Can we use "PNNL-JGCRI" as our institution ID? This is what our source ID looks like so far:

```
contact = "Rachel Hoesly (rachel.hoesly@pnnl.gov); Steve Smith (ssmith@pnnl.gov)";
further_info_url = "https://www.pnnl.gov/projects/ceds";
institution = "Pacific Northwest National Laboratory - Joint Global Change Research Institute, College Park, MD 20740, USA";
institution_id = "PNNL-JGCRI";
license_id = "CC BY 4.0";
mip_era = "CMIP6Plus";
source_version = "2024-07-08";
```

**Comment by durack1** [comment]
@znichollscr @ssmithclimate @rhoesly just need to circle on the DOI minting through Zenodo - Steve did you want to chat about this? And did you want the existing CMIP6Plus examples to peruse, e.g. https://www.wdc-climate.de/ui/cmip6?input=input4MIPs.CMIP6.CMIP.PCMDI.PCMDI-AMIP-1-1-9

**Comment by ssmithClimate** [comment]
We've done that. Here's what that looks like in our netCDF metadata:
 :doi = "10.5281/zenodo.13257219";

**Comment by durack1** [comment]
To just bring email discussions inline here, I was suggesting a format that follows `CEDS-CMIP-YYYY-MM-DD`, which brings things more inline with the other registered (and published) datasets: `CR-CMIP-0-3-0`, `SOLARIS-HEPPA-CMIP-4-3`, `PCMDI-AMIP-1-1-9`.

A comment from earlier this month (via email)
> A note, the source_id doesn’t include a grid_label, which is the way that I would be identifying these two different resolution datasets. You can of course add a resolution identifier into the source_id, but this will bloat things out a bit e.g., something like CEDS-CMIP-2024-08-06 to something like CEDS-CMIP-0p25-2024-08-06.`

So granularity for the PCMDI dataset, if we had two grid label versions would need to be `input4MIPs.CMIP6.CMIP.PCMDI.PCMDI-AMIP-1-1-9.gn` and that would then uniquely identify a source_id + grid_label/resolution dataset

**Comment by znichollscr** [comment]
Hi @ hahsan1, my apologies I somehow missed your first comment!

> Can we use "PNNL-JGCRI" as our institution ID?

Sure, and that's [already registered upstream](https://github.com/PCMDI/mip-cmor-tables/blob/jsonld/JSONLD/organisations/institutions/pnnl-jgcri.json) so nothing to do there.

> This is what our source ID looks like so far

Looks fine. Just to check, you're happy with the associated source ID being "CEDS-CMIP-YYYY-MM-DD" as Paul suggests in his comment and as I suggested in the issue description? You could obviously do e.g. "PNNL-JGCRI-YYYY-MM-DD" if you wanted instead.

> So granularity for the PCMDI dataset, if we had two grid label versions would need to be `input4MIPs.CMIP6.CMIP.PCMDI.PCMDI-AMIP-1-1-9.gn` and that would then uniquely identify a source_id + grid_label/resolution dataset

@durack1 just to check, you're talking about DOIs here right? If yes, I think this is just a question of title. I don't think it actually matters here as we have so much information now, we can always link the DOI to other metadata later if needed (because we have the full table, so can slice and dice how we wish).

**Comment by durack1** [comment]
> @durack1 just to check, you're talking about DOIs here right? If yes, I think this is just a question of title. I don't think it actually matters here as we have so much information now, we can always link the DOI to other metadata later if needed (because we have the full table, so can slice and dice how we wish).

Yep exactly, so attempting to keep some consistency with what happened last time (both in CMIP6 forcing datasets, and the CMIP6 model data) and what is happening moving forward. The **granularity** of the citation is something that Martina spent a lot of time on, and this discussion could be revisited if more strategic thinking was needed. With the CEDS zenodo DOIs, we want to make sure that the title of the zenodo page matches as neatly as possible to what the ESGF identifier is, so folks don't get confused trying to link one with another - although as Steve has noted the aspiration here is the write the DOI into the file metadata, so this would only be an issue if you didn't have the files available for perusal.

For ref here is the DKRZ citation landing page for the PCMDI data - https://www.wdc-climate.de/ui/cmip6?input=input4MIPs.CMIP6.CMIP.PCMDI.PCMDI-AMIP-1-1-9

**Comment by hahsan1** [comment]
> Looks fine. Just to check, you're happy with the associated source ID being "CEDS-CMIP-YYYY-MM-DD" as Paul suggests in his comment and as I suggested in the issue description? You could obviously do e.g. "PNNL-JGCRI-YYYY-MM-DD" if you wanted instead.
> 

Sounds good, I can change the source ID to "CEDS-CMIP-YYYY-MM-DD".

**Comment by znichollscr** [comment]
> The **granularity** of the citation is something that Martina spent a lot of time on, and this discussion could be revisited if more strategic thinking was needed

Ah ok. In that case, I think we've already got a clear case where the granularity that Martina chose doesn't work with Steve's approach. Steve wants a DOI for different grids. Martina's granularity doesn't allow that. So I think we're going to break the previous approach at least a little bit.

My suggestion would be to just go with whatever for now. We can always make something searchable in a custom way afterwards (because we have all the information at our fingertips now) and provide continuity that way. I don't think we need to impose a constraint on the data providers in advance?

**Comment by durack1** [comment]
Just so we have all options in front of us, here are two CMIP6 model data examples, with the first with granularity down to the experiment level, and second, at the model level (one level up)
https://www.wdc-climate.de/ui/cmip6?input=CMIP6.ScenarioMIP.NOAA-GFDL.GFDL-CM4.ssp585
https://www.wdc-climate.de/ui/cmip6?input=CMIP6.CMIP.EC-Earth-Consortium.EC-Earth3-LR

**Comment by durack1** [comment]
> I don't think we need to impose a constraint on the data providers in advance?

I agree with this statement, BUT note that the templates above have been highlighted as functional ways to do this, if we're able to ascertain resources to make this happen for CMIP7.. So I agree that it's completely up to the CEDS team to do what they like, but attempting to maintain some consistency with previous examples will make generating a DOI across both CMIP/historical period versions at differing resolutions, plus those for generated for the scenarios will be consistent, and hopefully a template that can be used by other input4MIPs contributors

**Comment by znichollscr** [comment]
Yep nice, on the same page 📖

**Comment by ssmithClimate** [comment]
I suspect this might be the first case of multiple resolutions, so could think of this as an extension?

**Comment by durack1** [comment]
@ssmithClimate this is true for input4MIPs, but across CMIP6 we did have a number of regridded datasets, for that project there was no delineation between them at the target granularity (and across the ~16 PB of contributions!).

To expand on the above, what we could do is just add another identifier, so for my example (if we did produce two resolutions), we could have

input4MIPs.CMIP6.CMIP.PCMDI.PCMDI-AMIP-1-1-9.gn - native resolution
input4MIPs.CMIP6.CMIP.PCMDI.PCMDI-AMIP-1-1-9.gr - regridded resolution (the grid_labels we've got assigned are , or maybe rather than gr=regridded, a more informative "01deg" or similar could be used. We've not done before, so a learning by doing example. For FYI, the grid_labels defined are [here](https://github.com/PCMDI/mip-cmor-tables/blob/main/MIP_grid_label.json)

**Comment by vnaik60** [comment]
Dont mean to distract from the original discussion, but is 
> the grid_labels defined are [here](https://github.com/PCMDI/mip-cmor-tables/blob/main/MIP_grid_label.json)

information made available somewhere for users who download data from ESGF? With so many grid options available now, it can get confusing for users. Providing a link to this information somewhere (maybe on [https://pcmdi.llnl.gov/mips/input4MIPs/](url) which is linked on the ESGF input4mips page) would be helpful.

**Comment by znichollscr** [comment]
This is a good question. My understanding is that there is a lot of work going on with these MIP/CMOR tables. Once that is settled, they will then provide a page we can link to which will spell things out for people. So, long-term, that might be the best solution.

As an interim solution, we could just add a list of these things to our README, then add links to that part of the README from other places?

**Comment by vnaik60** [comment]
Agree - both the long term and interim solutions sound good!

**Comment by znichollscr** [comment]
Cool, have made #89 to track that issue specifically

**Comment by vnaik60** [comment]
Thank you @znichollscr!

**Comment by durack1** [comment]
Yes we've been good at generating unique identifiers, BUT, these are far more useful when you have some documentation to link the unique identifier to useful information! Agreed, there is far more we can do to more explicitly document and define data, but first things first, get these live for folks to start using them

**Comment by ssmithClimate** [comment]
We're proposing now to have four source ID's for the CEDS data:
```
CEDS-CMIP-0p5-2024-07-08
CEDS-CMIP-0p5-2024-07-08-suppl
CEDS-CMIP-0p1-2024-07-08
CEDS-CMIP-0p1-2024-07-08-suppl
```
So that what are supplementary files and what are the primary data are clear.

**Comment by durack1** [comment]
> We're proposing now to have four source ID's for the CEDS data:
> 
> ```
> CEDS-CMIP-0p5-2024-07-08
> CEDS-CMIP-0p5-2024-07-08-suppl
> CEDS-CMIP-0p1-2024-07-08
> CEDS-CMIP-0p1-2024-07-08-suppl
> ```
> 
> So that what are supplementary files and what are the primary data are clear.

Sounds good Steve, this works for me. If you wanted to save 4 chars, you could collapse the `2024-07-08` to `240708`, assuming this is a YYMMDD format.

Just noting that in the ESGF Metagrid web interface these will be truncated to the below on-screen, with the full names preserved everywhere else (including for folks targeting a `source_id` for downloads)

```python
CEDS-CMIP-0p5-2024... the alternate above gets you CEDS-CMIP-0p5-2407...
CEDS-CMIP-0p5-2024...
CEDS-CMIP-0p1-2024...
CEDS-CMIP-0p1-2024...
```

**Comment by znichollscr** [comment]
> We're proposing now to have four source ID's for the CEDS data

Ok. I think it will be a permanent headache, but we can make this work. For completeness, I've repeated the reasons why I a single source ID is a better approach for our overall data handling (beyond just CEDS) below so they're in a public discussion. 

<details>
<summary>Reasons for using a single source ID</summary>

I would strongly advocate for the use of a single source ID. Using more than one source ID blurs the meaning of the term source ID. In my opinion, as a data user, this makes it much harder to understand and navigate the database.

Explaining in more detail:

At the moment, the source ID identifies the source of the data. All the other information about the data comes from other fields (e.g. grid label, resolution).

Considering the specific example of CEDS' data: if CEDS has multiple source IDs, one for the 0.5 degree data, one for the 0.1 degree data, one for supplementary 0.5 degree data and one for supplementary 0.1 degree data, then the source ID is not just the source of the data. Instead, the source ID contains information about a) the source of the data b) the grid and c) whether the data is 'main' or supplementary. For our database as a whole, the consequence is that that source ID identifies the source of the data, unless you're looking at anthropogenic emissions data, in which case source ID also defines your grid and whether the data is 'main' or supplementary.

From a user perspective, this conditionality of meaning makes life much, much more difficult. For example, in CMIP land, there is this 'table' component of the metadata. I can't tell you how many times I have tripped over the fact that "table" only defines variable names for most data, but for monthly data, table is also split by the realm of the data (you have to use "Amon", "Omon" etc. for monthly data, but for daily data it's just "day" and for three hourly data it's just "3hr"). I'd strongly suggest avoiding adding a similar conditionality of meaning to our input4MIPs data.

If there is information about the data that is missing from our current metadata capturing, we should add another field (see also proposal in #64), rather than changing the meaning of an existing field.

I understand the problems we're trying to solve with the different source IDs, however I think we're assuming things about our users that aren't true. Specifically, I would ask two questions (with follow ups):

- Have we ever received feedback that people couldn't use the grid label information to filter for the grid of interest to them?
    - If yes, is putting grid label information in the source ID the right solution?
- Has anyone ever complained that they downloaded too much data because they just downloaded everything for a given source ID (and didn't actually look at any of the variables supplied)?
    - If yes, is putting information about whether the data is 'main' or supplementary in the source ID the right solution? (Again, see the discussion in #64)

As I said, I think that having more than just source ID information in the source ID blurs the meaning of that field. If we go that route, dealing with the conditionality of meaning will be a headache we have to deal with forever. I think other options make more sense and we and our users would be better served with a single source ID.

</details>

**Comment by ssmithClimate** [comment]
The somewhat unique issue here for CEDS on the input data side of things is that we're now proposing to upload files with two different resolutions. The users have not seen this before. They are likely not going to catch the difference between gn and gr (since those really don't have a lot of meaning for CEDS anyway - that has more meaning for ESM data). So I think we need a way to get the resolution (e.g. "0p5 or 0p1) directly into the filename at minimum. 

The second issue is that the supplemental data is fundamentally different from the main data. We absolutely do not want people downloading, for example, solid biofuel emissions (supplemental data) and the primary emissions and adding them together. Which someone will definitely do, unless we make it very obvious that is probably not right. (And remember, many of the users are not native english speakers, so subtleties in metadata and/or documentation will for sure get lost for some.)

So giving these separate source IDs is something that shows up showing these as fundamentally different in the system, giving a strong indication that these are not the same animals and should not be put in the same coral together. 

Maybe there's a different way of doing that, but it needs to be something not very subtle or buried.

CEDS is a bit different - and perhaps stretching the system a bit - I'm not aware that other providers give data at different resolutions, over different time periods, or with large amounts of supplemental data (all of which CEDS is doing... :).

**Comment by durack1** [comment]
> So I think we need a way to get the resolution (e.g. "0p5 or 0p1) directly into the filename at minimum.

Thinking aloud (and without much forward thought), we could come up with a `grid_label` that was more informative than `gr` - `g0p5` or `g0p1` could work at first glance - that would give you your filename. I also note that @lchini is thinking about providing a regridded version of her data, but as this was just going to be standard regridding tools from their default grid, rather than any more sophisticated product. She had planned to see how the CEDS high res stuff was being downloaded before making the commitment to duplicate her work.

> The second issue is that the supplemental data is fundamentally different from the main data. We absolutely do not want people downloading, for example, solid biofuel emissions (supplemental data) and the primary emissions and adding them together.

I don't see the solution of labeling this as `supplemental` as solving that problem, once you provide data, it's amazing what downstream users will do with it. Rather this points to a need to clearly communicate what can and cannot/or should be done, rather than labelling files differently.

Just to repeat myself, I full expect (just like last time) there to be ongoing corrections that are required to subsets of the data, which will require us to deprecate some of the `CEDS-CMIP-2024-07-08` data and then mint a new source_id and new files with them. If we keep things as simple as possible (one source_id) then it makes it trivial to say use `CEDS-CMIP-2024-07-08`, but for CO2, and CH4 emissions use `CEDS-CMIP-2024-09-15` and for aircraft emissions use `CEDS-CMIP-2024-10-05` (or something, just going off the CMIP6 past experience). If we start with 4, then this becomes a considerable challenge to communicate (or more work, pick your favourite descriptor)

**Comment by znichollscr** [comment]
I fully acknowledge that I started this discussion, but perhaps now to suggest a way forward. 

Having thought about it more, I would suggest we go with @ssmithClimate's proposal and try with four source IDs. If we do this, one benefit is that we have (at least) two different approaches:

1. CEDS' multiple source ID approach
2. the GHG concentrations' single source ID approach

We can then see which one leads to more confusion for users, so we'll actually have data/information to help us with future decisions on this.

**Comment by durack1** [comment]
@znichollscr thanks for chiming in. Ultimately, this is @ssmithClimate's (and the team's) data, so as long as the data format conforms to what we can publish to ESGF, we can do anything that makes sense.

> We can then see which one leads to more confusion for users, so we'll actually have data/information to help us with future decisions on this.

I like your idea, see who creates more work for themselves (single source_id, or 4x) and then learn by doing.

@ssmithClimate let us know which way you want to go, so we can tweak our database of source_id registrations to reflect what is expected/will and imminently

**Comment by ssmithClimate** [comment]
I just looked in ESGF and last time we did have separate source ID's for base and supplemental data. So lets do that again.

So the 2nd question is the grid resolution. In ESGF search there are fields for Grid Label (which now shows up as "gn" is not easy to interpret) and also Nominal Resolution (which is easier to interpret). But this shows up as "gn" in the filename, so the user would need to rely on the metadata (or the search menu Nominal Resolution selection) to know the difference.

So that's my question to both of you for the resolution - which is sort of new - do we also separate that by source ID (I"m a bit agnostic about this - since it is in the interface in two places). Thoughts on that part?

**Comment by durack1** [comment]
> In ESGF search there are fields for Grid Label (which now shows up as "gn" is not easy to interpret) and also Nominal Resolution (which is easier to interpret).

Like with anything, if you know where to look, things become far clearer. For `grid_label` see [here](https://github.com/PCMDI/mip-cmor-tables/blob/main/MIP_grid_label.json) and for `nominal_resolution` see [here](https://github.com/PCMDI/mip-cmor-tables/blob/main/MIP_nominal_resolution.json) - note these are all templated from the CMIP6_CVs, so still keep their "model grid" heritage in comments. The intention of `grid_label` is to identify the native analysis grid, vs some interpolated grid, all relevant to a unique `source_id`.

> So that's my question to both of you for the resolution - which is sort of new - do we also separate that by source ID (I"m a bit agnostic about this - since it is in the interface in two places). Thoughts on that part?

I can speak for @znichollscr and me here, we've talked about this a lot. Keep it as simple (fewest source_id's) as we can, and use the identifiers that we have across *MIP data as a way to interpret what we have. The recommendation is that we mint the fewest source_id's we can (you've settled on `CEDS-CMIP-2024-07-08` and `CEDS-CMIP-2024-07-08-supplemental`), and then use a `grid_label` to identify the "native" data with `gn` and the "regridded" data with `gr`. So 2 source_id's and 2 grid_label's for each.

Is that clear?

**Comment by ssmithClimate** [comment]
Ok we'll go with two source ID's - as before.

**Comment by durack1** [comment]
Sounds good.

And just to satisfy my curiosity, your two resolutions, are these generated from the ground up at their resolution, or like land use, are you regridding your 0.5deg data to 0.1deg data?

**Comment by ssmithClimate** [comment]
A bit of both. Large point sources exist at their stated location independent of resolution. We downscale by sector everything else using (usually) EDGAR emissions as proxies. 

(If a proposal we just submitted is funded, we will significantly expand out point source database, and also explore using country-specific higher resolution proxy data.)

**Comment by durack1** [comment]
Nice I will be curious to learn a little more about this, whether you use a downscaling, objective-mapping, or what. Same problem in some ways with the ocean obs data, lots of point source snapshot measurements, with physics that ties together whether a single point data source is plausible, instrument error etc

**Comment by ssmithClimate** [comment]
It's fairly simple (in theory). Where we represent point sources, that is actual data (or what we feel is a solid estimation thereof), it's just a time series at every one of those points.

For the rest of the emissions it's just spatially distributed within each region by the spatial proxy data (with the specific point sources that we have included removed). We're generally doing the same thing regardless of the spatial resolution (although the actual coding methodology differs since there are more memory management issues at higher resolution).

**Comment by durack1** [comment]
@znichollscr FYI those data are coming down in the usual place, plus `SteveSmith-emissions/20240829/` - if you get to taking a peek at this before I do, I'd be curious if you spot anything that needs attention

**Comment by znichollscr** [comment]
Bulk emissions look all good to me.

For the VOC emissions, they currently have attributes "molecular weight" and "molecular weight unit". The CF-checker complains (rightly) about this. The attributes shouldn't have whitespace in the name I don't think, so I think these should be renamed to "molecular_weight" and "molecular_weight_unit" to avoid giving users whitespace headaches.

The warning I'm getting from the CF-checker is

```
WARN: (2.3): Global attribute : Attribute names should begin with a letter and be composed of letters, digits and underscores
WARN: (2.3): Global attribute  Attribute names should begin with a letter and be composed of letters, digits and underscores
```

**Comment by durack1** [comment]
> For the VOC emissions, they currently have attributes "molecular weight" and "molecular weight unit". The CF-checker complains (rightly) about this. The attributes shouldn't have whitespace in the name I don't think, so I think these should be renamed to "molecular_weight" and "molecular_weight_unit" to avoid giving users whitespace headaches.

@hahsan1 @ssmithClimate just circling on the above, did you want to recreate these VOC files to solve this issue, and just replace what you have in place? I'll then rerun the download, targeted and these files alone and start to get these in the ESGF publication queue

**Comment by ssmithClimate** [comment]
Yes, @hahsan1 is re-generating our files.

**Comment by durack1** [comment]
@ssmithClimate great, let me know when to start another download. FYI, @sashakames is on vacation until Tuesday, so there is not major rush to getting these done today - but if we had them in place on Tues, we might be able to get them live very soon thereafter

**Comment by durack1** [comment]
@hahsan1, @ssmithClimate please ping back on this issue when your new data is ready for download - @sashakames is back today, so it would be ideal if we can get this into the publication queue ASAP (if it is ready!)
