### ISSUE TITLE
Fix MRI-JRA55-do-1-6-0 license omission - CC BY 4.0

### ISSUE THREAD

**Issue by durack1** [PCMDI/input4MIPs_CVs#94]
The CMIP6Plus MRI-JRA55-do-1-6-0 dataset has a CC BY 4.0 license assigned, but this is not in our database - we need to correct that
```
(xcd061nctax) bash-4.2$ ncdump -h ../input4MIPs/CMIP6Plus/OMIP/MRI/MRI-JRA55-do-1-6-0/atmos/3hr/
prra/gr/v20240531/prra_input4MIPs_atmosphericState_OMIP_MRI-JRA55-do-1-6-0_gr_195801010130-
195812312230.nc | grep license
                :license = "OMIP boundary condition data produced by MRI is licensed under a Creative Commons
Attribution 4.0 International License (CC BY 4.0; https://creativecommons.org/licenses/by/4.0). Consult
https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing input4MIPs output, including citation
requirements and proper acknowledgment. Further information about this data, including some limitations,
can be found via the further_info_url (recorded as a global attribute in this file). The data producers and
data providers make no warranty, either express or implied, including, but not limited to, warranties of
merchantability and fitness for a particular purpose. All liabilities arising from the supply of the
information (including any liability arising in negligence) are excluded to the fullest extent permitted
by law" ;
```

**Comment by znichollscr** [comment]
If you look at https://pcmdi.github.io/input4MIPs_CVs/docs/input4MIPs_files_CMIP6Plus and filter for MRI, the license is there, it's just the license ID that isn't. In my head, that makes sense. We invented the idea of license ID after these files were published, so it would have been hard for them to conform.

Options I see:

a) leave as is
b) add a hack into our database/web page generation to manually write it in

I don't love option b because it causes our database to not match the files, but if it's really worth it we can do it.

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/b53da90d-4458-4da1-a383-ea078b4476fd">

**Comment by znichollscr** [comment]
> I would like to figure out a way to include it back in, and as we have stood up a database, surely it's just overwriting a None, isn't it?

Yep. Just chuck a manual fix in https://github.com/PCMDI/input4MIPs_CVs/blob/1c9c0b34e25ebe199a7dfbb78bf0e9a2237d6108/python-packages/input4MIPs-CVs/src/input4MIPs_CVs/cli/update-database.py#L206

**Comment by durack1** [comment]
@znichollscr got a PR in #99 for you to review, as I note in the PR notes, the fix is in there, but not sure how to integrate that into the DB, get it written to HTML files etc.. Learning by doing..
